// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMEPMb5BTu8Ul0nH__fFsxUfElF2Spksc',
    appId: '1:350881208409:web:d94ee54973ca59e74cb948',
    messagingSenderId: '350881208409',
    projectId: 'grocery-app-77c9b',
    authDomain: 'grocery-app-77c9b.firebaseapp.com',
    storageBucket: 'grocery-app-77c9b.appspot.com',
    measurementId: 'G-06JXW9L1NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6c3BMHI-EopJQPwUoT5-nduAIh8-ETE',
    appId: '1:350881208409:android:8371cea58d3082fb4cb948',
    messagingSenderId: '350881208409',
    projectId: 'grocery-app-77c9b',
    storageBucket: 'grocery-app-77c9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzx9xkzw-Zw4vntaWTM-Gs99s89bFoIwo',
    appId: '1:350881208409:ios:ce04f2f4b765bcd44cb948',
    messagingSenderId: '350881208409',
    projectId: 'grocery-app-77c9b',
    storageBucket: 'grocery-app-77c9b.appspot.com',
    iosClientId: '350881208409-vhdadvktdem9gp4n448u0i54es16gbc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzx9xkzw-Zw4vntaWTM-Gs99s89bFoIwo',
    appId: '1:350881208409:ios:ce04f2f4b765bcd44cb948',
    messagingSenderId: '350881208409',
    projectId: 'grocery-app-77c9b',
    storageBucket: 'grocery-app-77c9b.appspot.com',
    iosClientId: '350881208409-vhdadvktdem9gp4n448u0i54es16gbc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
